### ISSUE TITLE
Order creation while supplier list = empty

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#81]
Order creation phase: if supplier list is empty, the app stops (first attempt) or goes back to main menu (second attempt).

![Screenshot 2024-03-08 131055](https://github.com/BananaPilot/Team1-project/assets/30419423/353f3bce-9ecd-45a5-8fb6-d593e5f5bfa8)

![Screenshot 2024-03-08 131419](https://github.com/BananaPilot/Team1-project/assets/30419423/50663f42-c2c2-4a87-8404-37812c57f38e)

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/97
