### ISSUE TITLE
"The list is empty!" 

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#87]
Consider adding additional instructions when returning "The list is empty!".

![Screenshot 2024-03-08 151321](https://github.com/BananaPilot/Team1-project/assets/30419423/fb5016ba-c8d2-499b-a0af-7fd598a81b46)

Ex.: "The list is empty! Please add new product type first." (new supplier creation case, adjust to different instances)
**(if default components are created, the issue does not subsist)**

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/98
