### ISSUE TITLE
Product prompting formatting

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#88]
Product managment prompts "null" instead of "Input:"
0. is "Previos menu..." unlike other sections that indicate "Back to main menu" (prompt standardization)

![Screenshot 2024-03-08 152132](https://github.com/BananaPilot/Team1-project/assets/30419423/3c2fa15a-78c4-4d42-9bf5-d82e87744d3a)

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/98
