### ISSUE TITLE
New product creation: empty supplier list crashes the application

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#89]
![Screenshot 2024-03-08 153025](https://github.com/BananaPilot/Team1-project/assets/30419423/fb69d32d-1a6e-42bf-bd33-ad8444849420)

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/96

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/104/files
