### ISSUE TITLE
6. manage zones prompt

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#92]
Manage zones prompt doesn't have a "go back to previous/main menu option

![Screenshot 2024-03-08 191402](https://github.com/BananaPilot/Team1-project/assets/30419423/754199a3-5c83-4626-b199-5fb6c511ac57)

**Comment by BananaPilot** [comment]
XD cosa cazzo sta succedendo

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/103
