### ISSUE TITLE
Supplier search prompt error

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#93]
When choosing 5 - search by company name prompt leads to 6 - search by supplied product type

![Screenshot 2024-03-08 193832](https://github.com/BananaPilot/Team1-project/assets/30419423/587e5ab4-054c-47f1-857a-1adadd5f67c6)

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/99
