### ISSUE TITLE
Create new Product leads to index out of bounds and app crash

### ISSUE THREAD

**Issue by mmilasi** [BananaPilot/Team1-project#94]
![Screenshot 2024-03-08 194310](https://github.com/BananaPilot/Team1-project/assets/30419423/9507d2dc-c225-4ac7-897a-a29571ee6fd0)

**Comment by BananaPilot** [comment]
forse fixato con https://github.com/BananaPilot/Team1-project/pull/96 prova a vedere

**Comment by BananaPilot** [comment]
https://github.com/BananaPilot/Team1-project/pull/104/files
